version: '3'

services:
  app:
    build: .
    container_name: api_estacionamentos
    command: "sh -c 'npm install && npm run start:dev'"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: "db_api_estacionamentos"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}   
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    ports:
      - 3306:3306
